"""t.verifiers.framac — the sixth kernel: Frama-C/WP over ACSL contracts.

Pins: Frama-C 33.0 (Arsenic) + alt-ergo 2.4.3-free (NEVER opam's alt-ergo
2.6.x, which is non-commercial — the WS-7 licensing catch), via opam.

THE REFUTED DOCTRINE, decided after measurement: a false postcondition here
surfaces as Stepout/Timeout on the goal — the quantified VC yields no
countermodel from alt-ergo or plain Z3 (both measured 2026-08-31). That is
the same epistemic position as Dafny's rlimit and gnatprove's `medium`: the
deterministic budget IS the bar, and "unproved at the pinned budget" is what
REFUTED means operationally. The per-goal status lines ship in extras so the
countermodel refinement (why3's `counterexamples` prover configs exist; WP's
naming for them is the parked follow-up) can sharpen this later without
rewriting history. Outcome.TIMEOUT here means the WALL backstop only.

THE SEMANTIC DECISION: without -wp-rte, WP reasons about C integer
arithmetic mathematically — which is t v0's semantics, so -wp-rte is
deliberately absent. The machine-int arm (with -wp-rte and explicit range
obligations) is a later gate, same as Verus's exec/i64 arm.

-wp-cache none because a proof cache poisons flake_check — a cached verdict
re-measures nothing.

THE AUDIT ARCHITECTURE (Wave-2, all points measured 2026-08-31):

* VERIFIED requires the positive line `[wp] Proved goals: N / N` with N >= 1,
  anchored at start-of-line and taken from the LAST occurrence, plus exit 0.
  Source echoes in kernel diagnostics are indented with a line number
  (measured on parse_error.c), so a source line cannot forge the anchor.
* The ban scan runs on the kernel's OWN normalized view (`frama-c -print`):
  macros are expanded (macro_axiom.c), backslash-newline splices are undone
  (splice_axiom.c), and plain C comments are dropped (overfire_admit.c) —
  three evasions the raw regex provably mis-scores. Raw-text scanning is only
  the fallback when the file does not parse, where VERIFIED is unreachable.
* `axiomatic`/`axiom` are banned because WP assumes axioms globally and emits
  NO goal for them: axiom_false.c and axiom_nofalse.c both closed
  `Proved goals: 4 / 4` over a false axiom. `lemma` and `check` are NOT
  banned: their obligations are emitted (lemma_false.c measured 4/5).
* -wp-smoke-tests is pinned: WP tries to derive \false from each contract's
  hypotheses, and an inconsistent contract is reported `(Doomed)` /
  `Failed smoke-test` -> VACUOUS. This catches what no literal regex can:
  `requires 0 == 1` measured Doomed; all 11 honest tasks stay N / N and all
  11 twins stay N < M with the flag on (measured across out/*.c).
* TOOL_ERROR is live: absent/dead kernel binary, empty kernel output,
  `[wp] User Error` / `Plug-in wp aborted` (measured with an unknown prover:
  exit 0, no Proved line — exit codes alone cannot be trusted), and a
  `Failed:` prover status outside a smoke test. A prover failure is never
  REFUTED — it is not evidence.
"""
from __future__ import annotations

import re
import subprocess
import time
from pathlib import Path

from . import Outcome, Result, safe_text, sha256_file
from .discover import find, missing

FRAMAC = find("T_FRAMAC", ['frama-c'], [".opam/*/bin/frama-c"])
_FRAMAC_WHY = missing("framac", "T_FRAMAC", ['frama-c'], [".opam/*/bin/frama-c"])
DEFAULT_STEPS = 20_000
WALL_S = 240
PRINT_WALL_S = 60

# admit/assumes discharge goals by fiat at the use site; axiomatic/axiom are
# assumed globally with no emitted goal (see module docstring, measured);
# `requires \false` kept although smoke tests subsume it — the regex is the
# second line and costs nothing.
BANNED = re.compile(
    r"\badmit\b|\bassumes\b|\baxiomatic\b|\baxiom\b|requires\s+\\false",
    re.IGNORECASE)

# Cyrillic/Greek confusables folded to ASCII before the raw fallback scan
# (homoglyph_axiom.c: frama-c rejects the homoglyph identifier -> MALFORMED
# regardless; the fold only upgrades the fallback label, never gates VERIFIED).
_FOLD = str.maketrans({
    "а": "a", "е": "e", "о": "o", "р": "p", "с": "c", "х": "x", "у": "y",
    "і": "i", "ѕ": "s", "ԁ": "d", "ɑ": "a", "α": "a", "ο": "o", "τ": "t",
    "ι": "i", "А": "A", "Е": "E", "О": "O", "С": "C", "Р": "P", "Х": "X"})

_PROVED = re.compile(r"^\[wp\] Proved goals:\s*(\d+)\s*/\s*(\d+)\s*$", re.M)
_STATUS = re.compile(r"^\s+(Qed|Alt-Ergo|Timeout|Stepout|Unknown|Failed)"
                     r":?\s+\d+", re.M)
_DOOMED = re.compile(r"Failed smoke-test|\(Doomed\)")
_SMOKE = re.compile(r"^\s+Smoke Tests:\s+(\d+)\s*/\s*(\d+)", re.M)
_FAILED = re.compile(r"^\s+Failed:\s+\d+", re.M)
_TOOLFAIL = re.compile(r"Plug-in wp aborted|\[wp\] User Error")
_PRINT_MARK = "/* Generated by Frama-C */"


def version() -> str:
    if not FRAMAC:
        raise SystemExit(_FRAMAC_WHY)
    p = subprocess.run([FRAMAC, "-version"], capture_output=True, text=True)
    return f"frama-c {p.stdout.strip()} / alt-ergo 2.4.3-free"


def _ver() -> str:
    try:
        return version()
    except (SystemExit, OSError):
        return "frama-c (unavailable)"


def _run(cmd: list, wall: int):
    """(returncode, decoded output). Decoded errors='replace' because kernel
    diagnostics echo raw source bytes — text=True would re-crash on the very
    non-UTF8 probes safe_text exists for."""
    p = subprocess.run(cmd, capture_output=True, timeout=wall)
    return p.returncode, (p.stdout.decode("utf-8", errors="replace")
                          + p.stderr.decode("utf-8", errors="replace"))


def verify(path: Path, budget: int = DEFAULT_STEPS) -> Result:
    src_hash = sha256_file(path)
    t0 = time.monotonic()
    if not FRAMAC:
        return Result("framac", "frama-c (absent)", src_hash,
                      Outcome.TOOL_ERROR, budget=f"wp-steps={budget}",
                      error=_FRAMAC_WHY)

    # The t lowering emits UTF-8 only, so a non-decodable source is not a t
    # artifact: MALFORMED, before any kernel run. Measured 2026-08-31 without
    # this gate: frama-c 33 accepts raw bytes inside a plain comment and
    # proves the goals (nonutf8.c scored VERIFIED), and 10MB of random bytes
    # (random10mb.c) burned the full wall backstop.
    try:
        path.read_bytes().decode("utf-8")
    except UnicodeDecodeError as e:
        return Result("framac", _ver(), src_hash, Outcome.MALFORMED,
                      wall_ms=int((time.monotonic() - t0) * 1000),
                      budget=f"wp-steps={budget}",
                      error=f"source is not valid UTF-8: {e}")

    # Ban audit on the kernel's normalized view; the scan starts after the
    # print marker so the echoed source PATH (e.g. axiom_false.c in the
    # Parsing line) cannot trip the regex.
    print_ok, norm = False, ""
    try:
        rc_p, norm = _run([FRAMAC, "-no-autoload-plugins", "-print",
                           str(path)], PRINT_WALL_S)
        print_ok = rc_p == 0 and _PRINT_MARK in norm
    except (subprocess.TimeoutExpired, OSError):
        pass
    if print_ok:
        banned = BANNED.findall(norm.split(_PRINT_MARK, 1)[1])
        ban_audit = "kernel-normalized (-print)"
    else:
        raw = safe_text(path)
        banned = BANNED.findall(raw) or BANNED.findall(raw.translate(_FOLD))
        ban_audit = "raw fallback (unparseable source)"
    if banned:
        return Result("framac", _ver(), src_hash, Outcome.VACUOUS,
                      wall_ms=int((time.monotonic() - t0) * 1000),
                      budget=f"wp-steps={budget}",
                      extras={"banned_tokens": banned[:5],
                              "ban_audit": ban_audit})

    try:
        rc, out = _run(
            [FRAMAC, "-wp", "-wp-prover", "alt-ergo", "-wp-steps",
             str(budget), "-wp-cache", "none", "-wp-smoke-tests", str(path)],
            WALL_S)
    except subprocess.TimeoutExpired:
        return Result("framac", _ver(), src_hash, Outcome.TIMEOUT,
                      wall_ms=int((time.monotonic() - t0) * 1000),
                      budget=f"wp-steps={budget}", error="wall backstop fired")
    except OSError as e:
        return Result("framac", _ver(), src_hash, Outcome.TOOL_ERROR,
                      wall_ms=int((time.monotonic() - t0) * 1000),
                      budget=f"wp-steps={budget}",
                      error=f"kernel binary failed to run: {e}")
    wall = int((time.monotonic() - t0) * 1000)
    proved = list(_PROVED.finditer(out))
    m = proved[-1] if proved else None
    statuses = _STATUS.findall(out)
    smoke = _SMOKE.search(out)
    err = ""

    if not out.strip():
        outcome = Outcome.TOOL_ERROR
        err = "kernel produced empty output"
    elif _DOOMED.search(out) or (smoke and smoke.group(1) != smoke.group(2)):
        outcome = Outcome.VACUOUS       # contract hypotheses derive \false
    elif _TOOLFAIL.search(out):
        outcome = Outcome.TOOL_ERROR    # plugin/prover infrastructure failure
        err = out[-400:]
    elif m is None:
        outcome = Outcome.MALFORMED     # WP never reached goal generation
    elif int(m.group(2)) == 0:
        outcome = Outcome.MALFORMED     # zero proof obligations is no theorem
    elif _FAILED.search(out):
        outcome = Outcome.TOOL_ERROR    # prover failure outside a smoke test
        err = out[-400:]
    elif int(m.group(1)) == int(m.group(2)):
        if rc == 0 and print_ok:
            outcome = Outcome.VERIFIED
        else:
            outcome = Outcome.TOOL_ERROR  # all-proved without a clean exit
            err = out[-400:]              # or without the controlled ban audit
    else:
        outcome = Outcome.REFUTED       # unproved at the pinned budget
    return Result("framac", _ver(), src_hash, outcome,
                  ok=outcome == Outcome.VERIFIED, exit_code=rc,
                  wall_ms=wall, budget=f"wp-steps={budget}", error=err,
                  extras={"proved": m.group(0).replace("[wp] ", "").strip()
                          if m else None,
                          "goal_statuses": statuses[:8],
                          "smoke": smoke.group(0).strip() if smoke else None,
                          "banned_tokens": [],
                          "ban_audit": ban_audit})
