#!/usr/bin/env python3
"""t/make_grammar.py -- generate t.gbnf's identifier rule from the lexer's own keyword set (2026-09-18).

    python3 t/make_grammar.py [--grammar t/t.gbnf] [--check]

GBNF has no negative lookahead, so "a word that is not a keyword" cannot be written by hand as `[A-Za-z]
[A-Za-z0-9_]*` minus a list. It can be generated: the keywords form a trie, and an identifier is any word that
either leaves the trie at some character or runs past a keyword without stopping on one. That is a plain
context-free grammar with one rule per trie node, and this writes it.

Generating it from `surface.KEYWORDS` rather than restating the list keeps the grammar from drifting when a
keyword is added to the notation: run this, and `t/grammar_check.py` proves the result still agrees with the
parser. `--check` exits non-zero if the file on disk is not what this would write, which is the form for a test.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import surface                                                  # noqa: E402

BEGIN = "# BEGIN generated by t/make_grammar.py -- an identifier is a word that is not a keyword"
END = "# END generated"

# the characters an identifier may hold, as GBNF ranges, so a class can be written minus a few characters
START = [("A", "Z"), ("a", "z")]
REST = [("A", "Z"), ("a", "z"), ("0", "9"), ("_", "_")]


def klass(ranges: list[tuple[str, str]], without: set[str]) -> str:
    """A GBNF character class over `ranges` with `without` removed, as the fewest ranges that says it."""
    chars = []
    for lo, hi in ranges:
        chars += [chr(c) for c in range(ord(lo), ord(hi) + 1)]
    keep = [c for c in chars if c not in without]
    if not keep:
        return ""
    out, start, prev = [], keep[0], keep[0]
    for c in keep[1:]:
        if ord(c) == ord(prev) + 1:
            prev = c
            continue
        out.append((start, prev))
        start = prev = c
    out.append((start, prev))
    esc = lambda ch: ch.replace("\\", "\\\\").replace("]", "\\]").replace("^", "\\^").replace("-", "\\-")  # noqa: E731
    return "[" + "".join(esc(a) if a == b else f"{esc(a)}-{esc(b)}" for a, b in out) + "]"


def rules(keywords: set[str]) -> str:
    """One rule per trie node. `id-n` is what may follow the prefix that reached node n: any character that
    leaves the trie (and then anything), any character that stays in it (and then that node's rule), and the
    empty string only where the prefix is a word that is not itself a keyword."""
    nodes: list[dict] = [{}]                                    # node 0 is the empty prefix
    words: list[str] = [""]
    for kw in sorted(keywords):
        n = 0
        for ch in kw:
            if ch not in nodes[n]:
                nodes.append({})
                words.append(words[n] + ch)
                nodes[n][ch] = len(nodes) - 1
            n = nodes[n][ch]

    lines = [BEGIN,
             f"# {len(keywords)} keywords, {len(nodes)} trie nodes, from surface.KEYWORDS -- do not hand-edit",
             "id ::= id-0",
             "idrest ::= " + klass(REST, set()) + "*"]
    for n, kids in enumerate(nodes):
        alts = []
        ranges = START if n == 0 else REST
        # a character that leaves the trie: after it, anything an identifier may hold
        out = klass(ranges, set(kids))
        if out:
            alts.append(f"{out} idrest")
        for ch, child in sorted(kids.items()):
            if n == 0 and not ch.isalpha():
                continue                                        # an identifier cannot start with a digit or _
            alts.append(f"\"{ch}\" id-{child}")
        if n != 0 and words[n] not in keywords:
            alts.append("\"\"")                                 # the word may end here: it is not a keyword
        lines.append(f"id-{n} ::= " + " | ".join(alts))
    lines.append(END)
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--grammar", type=Path, default=HERE / "t.gbnf")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = a.grammar.read_text(encoding="utf-8")
    body = rules(set(surface.KEYWORDS))
    if BEGIN in text:
        head, _, rest = text.partition(BEGIN)
        _, _, tail = rest.partition(END + "\n")
        new = head + body + tail
    else:
        new = text.rstrip("\n") + "\n\n" + body
    if a.check:
        same = new == text
        print("t.gbnf holds the generated rule" if same else
              "t.gbnf is out of date: run python3 t/make_grammar.py")
        return 0 if same else 1
    a.grammar.write_text(new, encoding="utf-8")
    print(f"{len(surface.KEYWORDS)} keywords written into {a.grammar.relative_to(HERE.parent)} "
          f"as {body.count('::=')} rules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
